Medica/Models/Paciente.cs
namespace Medica
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    [Table("Pacientes")]
    public partial class Paciente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Paciente()
        {
            Consulta = new HashSet<Consulta>();
        }

        [Key]
        [Column(TypeName = "numeric")]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public decimal PacienteId { get; set; }

        [Required]
        [StringLength(500)]
        public string Nombres { get; set; }

        [Required]
        [StringLength(100)]
        public string ApellidoPaterno { get; set; }

        [StringLength(100)]
        public string ApellidoMaterno { get; set; }

        [Column(TypeName = "numeric")]
        public decimal Telefono { get; set; }

        [StringLength(500)]
        public string Direccion { get; set; }

        [Column(TypeName = "numeric")]
        public decimal GeneroID { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulta> Consulta { get; set; }

        public virtual Genero Genero { get; set; }
    }
}

Medica/Controllers/ConsultasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Medica;
using DayPilot.Web.Mvc.Json;
using Medica.Models;

namespace Medica.Controllers
{
    public class ConsultasController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Consultas
        public ActionResult Index()
        {
            var consulta = db.Consulta.Include(c => c.Medico).Include(c => c.Paciente);
            return View(consulta.ToList());
        }

        // GET: Consultas By PacientId
        public ActionResult SearchByPacientId(int PacienteId)
        {
            //var consulta = db.Consulta.Include(c => c.Medico).Include(c => c.Paciente);
            List<Consulta> ListaConsultas = db.Consulta.SqlQuery ( @"select * from consulta where pacienteId = " + PacienteId).ToList();
            return View(ListaConsultas);
        }


        // GET: Consultas ListView
        public ActionResult ListView()
        {
            var consulta = db.Consulta.Include(c => c.Medico).Include(c => c.Paciente);
            return View(consulta.ToList());
        }

        // GET: Consultas/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consulta.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            return View(consulta);
        }

        // GET: Consultas/Create
        public ActionResult Create()
        {
            ViewBag.MedicoId = new SelectList(db.Medico, "MedicoID", "Nombre");
            ViewBag.PacienteId = new SelectList(db.Paciente, "PacienteId", "Nombres");
            return View();
        }

        // GET: Consultas/Create
        public ActionResult CreateDated(DateTime Fecha, DateTime FechaFin)
        {
            ViewBag.MedicoId = new SelectList(db.Medico, "MedicoID", "Nombre");
            ViewBag.PacienteId = new SelectList(db.Paciente, "PacienteId", "Nombres");
            Consulta consulta = new Consulta();
            consulta.Fecha = Fecha;
            consulta.FechaFin = FechaFin;
            return View(consulta);
        }

        // POST: Consultas/CreateDated
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreateDated([Bind(Include = "ConsultaId,MedicoId,PacienteId,Fecha,Sintomas,Diagnostico,Tratamiento,Observaciones, FechaFin")] Consulta consulta)
        {
            if (ModelState.IsValid)
            {
                db.Consulta.Add(consulta);
                db.SaveChanges();
                //return RedirectToAction("Index");
                return JavaScript(SimpleJsonSerializer.Serialize("OK"));
                
            }

            ViewBag.MedicoId = new SelectList(db.Medico, "MedicoID", "Nombre", consulta.MedicoId);
            ViewBag.PacienteId = new SelectList(db.Paciente, "PacienteId", "Nombres", consulta.PacienteId);

            return View(consulta);
            //return JavaScript(SimpleJsonSerializer.Serialize("OK"));
        }

        // POST: Consultas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ConsultaId,MedicoId,PacienteId,Fecha,Sintomas,Diagnostico,Tratamiento,Observaciones, FechaFin")] Consulta consulta)
        {
            if (ModelState.IsValid)
            {
                db.Consulta.Add(consulta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.MedicoId = new SelectList(db.Medico, "MedicoID", "Nombre", consulta.MedicoId);
            ViewBag.PacienteId = new SelectList(db.Paciente, "PacienteId", "Nombres", consulta.PacienteId);
            return View(consulta);
        }

        // GET: Consultas/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consulta.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            ViewBag.MedicoId = new SelectList(db.Medico, "MedicoID", "Nombre", consulta.MedicoId);
            ViewBag.PacienteId = new SelectList(db.Paciente, "PacienteId", "Nombres", consulta.PacienteId);
            return View(consulta);
        }

        // POST: Consultas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ConsultaId,MedicoId,PacienteId,Fecha,Sintomas,Diagnostico,Tratamiento,Observaciones, FechaFin")] Consulta consulta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(consulta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.MedicoId = new SelectList(db.Medico, "MedicoID", "Nombre", consulta.MedicoId);
            ViewBag.PacienteId = new SelectList(db.Paciente, "PacienteId", "Nombres", consulta.PacienteId);
            return View(consulta);
        }

        // GET: Consultas/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Consulta consulta = db.Consulta.Find(id);
            if (consulta == null)
            {
                return HttpNotFound();
            }
            return View(consulta);
        }

        // POST: Consultas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Consulta consulta = db.Consulta.Find(id);
            db.Consulta.Remove(consulta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Medica/Controllers/PacientesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Medica;
using Medica.Models;

namespace Medica.Controllers
{
    public class PacientesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Pacientes
        public ActionResult Index()
        {
            var paciente = db.Paciente.Include(p => p.Genero);
            return View(paciente.ToList());
        }

        // GET: Pacientes/Details/5
        public ActionResult Details(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // GET: Pacientes/Create
        public ActionResult Create()
        {
            ViewBag.GeneroID = new SelectList(db.Genero, "GeneroId", "Descripcion");
            return View();
        }

        // POST: Pacientes/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PacienteId,Nombres,ApellidoPaterno,ApellidoMaterno,Telefono,Direccion,GeneroID")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.Paciente.Add(paciente);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.GeneroID = new SelectList(db.Genero, "GeneroId", "Descripcion", paciente.GeneroID);
            return View(paciente);
        }
        
        // GET: Pacientes/Edit/5
        public ActionResult Edit(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            ViewBag.GeneroID = new SelectList(db.Genero, "GeneroId", "Descripcion", paciente.GeneroID);
            return View(paciente);
        }

        // POST: Pacientes/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que desea enlazarse. Para obtener 
        // más información vea http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "PacienteId,Nombres,ApellidoPaterno,ApellidoMaterno,Telefono,Direccion,GeneroID")] Paciente paciente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(paciente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.GeneroID = new SelectList(db.Genero, "GeneroId", "Descripcion", paciente.GeneroID);
            return View(paciente);
        }

        // GET: Pacientes/Delete/5
        public ActionResult Delete(decimal id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Paciente paciente = db.Paciente.Find(id);
            if (paciente == null)
            {
                return HttpNotFound();
            }
            return View(paciente);
        }

        // POST: Pacientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(decimal id)
        {
            Paciente paciente = db.Paciente.Find(id);
            db.Paciente.Remove(paciente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Medica/Views/Pacientes/Create.cshtml
@model Medica.Paciente

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoPaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoPaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoMaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoMaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroID, "GeneroID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Medica/Views/Pacientes/Delete.cshtml
@model Medica.Paciente

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoPaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoPaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoMaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoMaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Medica/Views/Pacientes/Details.cshtml
@model Medica.Paciente

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Paciente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genero.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genero.Descripcion)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nombres)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombres)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoPaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoPaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApellidoMaterno)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApellidoMaterno)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telefono)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telefono)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Direccion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Direccion)
        </dd>

    </dl>
</div>
<div>
    <h4>Historial</h4>
    @Html.BeginForm("SearchByPacientId","Consultas")
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PacienteId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Medica/Views/Pacientes/Edit.cshtml
@model Medica.Paciente

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Paciente</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PacienteId)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombres, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombres, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nombres, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoPaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoPaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoPaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ApellidoMaterno, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ApellidoMaterno, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ApellidoMaterno, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telefono, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telefono, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telefono, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Direccion, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Direccion, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Direccion, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GeneroID, "GeneroID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GeneroID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GeneroID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-2.1.4.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

Medica/Views/Pacientes/Index.cshtml
@model IEnumerable<Medica.Paciente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Genero.Descripcion)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombres)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApellidoPaterno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApellidoMaterno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Telefono)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Direccion)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Genero.Descripcion)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nombres)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApellidoPaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApellidoMaterno)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Telefono)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Direccion)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.PacienteId }) |
            @Html.ActionLink("Details", "Details", new { id=item.PacienteId }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.PacienteId })
        </td>
    </tr>
}

</table>